In [28]:
import numpy as np
n_row, n_col = 10, 3
edge_start = np.repeat(np.arange(n_row), n_col)
edge_end = np.tile(np.arange(n_row, n_row + n_col), n_row)
print(edge_start.shape, edge_end.shape)
print(edge_start[:20], edge_end[:20])

edge_start_new = np.concatenate((edge_start, edge_end))
edge_end_new = np.concatenate((edge_end, edge_start))
print(edge_start_new.shape, edge_end_new.shape)
print(edge_start_new, edge_end_new)



(30,) (30,)
[0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6] [10 11 12 10 11 12 10 11 12 10 11 12 10 11 12 10 11 12 10 11]
(60,) (60,)
[ 0  0  0  1  1  1  2  2  2  3  3  3  4  4  4  5  5  5  6  6  6  7  7  7
  8  8  8  9  9  9 10 11 12 10 11 12 10 11 12 10 11 12 10 11 12 10 11 12
 10 11 12 10 11 12 10 11 12 10 11 12] [10 11 12 10 11 12 10 11 12 10 11 12 10 11 12 10 11 12 10 11 12 10 11 12
 10 11 12 10 11 12  0  0  0  1  1  1  2  2  2  3  3  3  4  4  4  5  5  5
  6  6  6  7  7  7  8  8  8  9  9  9]


In [33]:
masked_sample_index = [0,2]
# masked_sample_index = torch.tensor(masked_sample_index)
mask_start = ~np.isin(edge_start_new, masked_sample_index)
mask_end = ~np.isin(edge_end_new, masked_sample_index)
overal_mask = np.logical_and(mask_start, mask_end)
print(mask_start)
print(mask_end)
print(overal_mask)

[False False False  True  True  True False False False  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True False False False  True  True  True
 False False False  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True]
[False False False  True  True  True False False False  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True False False False  True  True  True
 False False False  True  True  True  True  True 

In [66]:
from sklearn.model_selection import KFold
import pandas as pd 
kf = KFold(n_splits=5, shuffle=True, random_state=42)
data=pd.read_csv('uci/raw_data/adult/data/data.txt', sep=' ', header=None, names=[str(x)for x in range(1)])
for index, (train_index, test_index) in enumerate(kf.split(data)):
    # print(train_index)
    print(test_index)
    np.savetxt("uci/raw_data/adult/data/index_test_{}.txt".format(index), test_index, fmt = '%d')
    hi = np.loadtxt("uci/raw_data/adult/data/index_test_{}.txt".format(index),dtype=int)
    print(hi)

[    1     4     6 ... 48821 48824 48830]
[    1     4     6 ... 48821 48824 48830]
[    0    11    13 ... 48832 48833 48835]
[    0    11    13 ... 48832 48833 48835]
[    3     8    14 ... 48825 48840 48841]
[    3     8    14 ... 48825 48840 48841]
[    5    15    18 ... 48836 48837 48838]
[    5    15    18 ... 48836 48837 48838]
[    2     9    10 ... 48823 48827 48839]
[    2     9    10 ... 48823 48827 48839]
