In [28]:
import numpy as np
n_row, n_col = 10, 3
edge_start = np.repeat(np.arange(n_row), n_col)
edge_end = np.tile(np.arange(n_row, n_row + n_col), n_row)
print(edge_start.shape, edge_end.shape)
print(edge_start[:20], edge_end[:20])

edge_start_new = np.concatenate((edge_start, edge_end))
edge_end_new = np.concatenate((edge_end, edge_start))
print(edge_start_new.shape, edge_end_new.shape)
print(edge_start_new, edge_end_new)



(30,) (30,)
[0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6] [10 11 12 10 11 12 10 11 12 10 11 12 10 11 12 10 11 12 10 11]
(60,) (60,)
[ 0  0  0  1  1  1  2  2  2  3  3  3  4  4  4  5  5  5  6  6  6  7  7  7
  8  8  8  9  9  9 10 11 12 10 11 12 10 11 12 10 11 12 10 11 12 10 11 12
 10 11 12 10 11 12 10 11 12 10 11 12] [10 11 12 10 11 12 10 11 12 10 11 12 10 11 12 10 11 12 10 11 12 10 11 12
 10 11 12 10 11 12  0  0  0  1  1  1  2  2  2  3  3  3  4  4  4  5  5  5
  6  6  6  7  7  7  8  8  8  9  9  9]


In [33]:
masked_sample_index = [0,2]
# masked_sample_index = torch.tensor(masked_sample_index)
mask_start = ~np.isin(edge_start_new, masked_sample_index)
mask_end = ~np.isin(edge_end_new, masked_sample_index)
overal_mask = np.logical_and(mask_start, mask_end)
print(mask_start)
print(mask_end)
print(overal_mask)

[False False False  True  True  True False False False  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True False False False  True  True  True
 False False False  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True]
[False False False  True  True  True False False False  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True False False False  True  True  True
 False False False  True  True  True  True  True 

In [3]:
from sklearn.model_selection import KFold
import pandas as pd 
import numpy as np
kf = KFold(n_splits=5, shuffle=True, random_state=42)
DATA_NAMES = ['adult','compas','eye_movements_num','eye_movements_cat']
for DATA_NAME in DATA_NAMES:
    print(DATA_NAME)
    data=pd.read_csv('uci/raw_data/'+DATA_NAME+'/data/data.txt', sep=' ', header=None, names=[str(x)for x in range(1)])
    for index, (train_index, test_index) in enumerate(kf.split(data)):
        # print(train_index)
        print(len(test_index))
        np.savetxt("uci/raw_data/"+DATA_NAME+"/data/index_test_{}.txt".format(index), test_index, fmt = '%d')

adult
[    1     4     6 ... 48821 48824 48830]
[    1     4     6 ... 48821 48824 48830]
[    0    11    13 ... 48832 48833 48835]
[    0    11    13 ... 48832 48833 48835]
[    3     8    14 ... 48825 48840 48841]
[    3     8    14 ... 48825 48840 48841]
[    5    15    18 ... 48836 48837 48838]
[    5    15    18 ... 48836 48837 48838]
[    2     9    10 ... 48823 48827 48839]


[    2     9    10 ... 48823 48827 48839]
compas
[   8   12   17   19   23   26   29   33   43   45   47   51   61   65
   68   69   70   79   84   90   93   95   96   99  100  106  109  120
  122  132  134  135  139  144  149  150  151  157  166  168  175  177
  179  184  191  192  195  196  199  203  210  214  218  219  227  228
  230  233  238  239  240  248  251  252  254  274  279  287  290  291
  296  297  298  308  315  318  322  350  351  354  366  367  371  373
  376  378  387  393  410  414  415  416  422  426  429  438  443  450
  457  463  465  468  471  472  478  485  486  491  497  501  505  511
  517  527  530  533  534  538  544  549  553  555  561  567  568  577
  582  584  586  589  594  596  598  599  602  605  621  624  625  626
  633  642  644  653  655  657  668  670  676  677  681  683  691  693
  705  711  718  720  721  724  731  733  734  742  746  751  756  759
  763  764  765  776  787  794  798  800  802  805  807  810  811  812
  828  829  831  833  838  8

FileNotFoundError: [Errno 2] No such file or directory: 'uci/raw_data/eye_movements_num/data/data.txt'